server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:bookings
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

booking:
  quarterlyDuration: 15
  halfHourlyDuration: 30
  hourlyDuration: 60
  minimumStartTime: '08:30'
  maximumEndTime: '23:30'
  maintenanceSlot:
    MORNING:
      startTime: '09:00'
      endTime: '09:15'
    NOON:
      startTime: '13:00'
      endTime: '13:15'
    EVENING:
      startTime: '23:15'
      endTime: '23:30'



